### ISSUE TITLE
Not working with Baikal server

### ISSUE THREAD

**Issue by deimjons** [Adi146/ContactsBDayCalendar#1]
Hello, I tried to use this script but got an error. The server configuration was tested with davx5, and the credentials are working. Is it work with Baikal server?

My command:

`docker run --env WEBDAV_CONTACTS_URL=https://baikal.example.com/dav.php/addressbooks/alex/default/ --env WEBDAV_CALENDAR_URL=https://baikal.example.com/dav.php/calendars/alex/contact-bdays/ --env WEBDAV_USER=alex --env WEBDAV_PASSWORD=mypassword ghcr.io/adi146/contacts_bday_calendar:latest`

Logs:

```
Traceback (most recent call last):
  File "//birthday_calendar.py", line 40, in <module>
    for vcf_file in contacts_client.list('/'):
  File "/usr/local/lib/python3.10/site-packages/webdav3/client.py", line 67, in _wrapper
    res = fn(self, *args, **kw)
  File "/usr/local/lib/python3.10/site-packages/webdav3/client.py", line 264, in list
    response = self.execute_request(action='list', path=directory_urn.quote())
  File "/usr/local/lib/python3.10/site-packages/webdav3/client.py", line 230, in execute_request
    raise ResponseErrorCode(url=self.get_url(path), code=response.status_code, message=response.content)
webdav3.exceptions.ResponseErrorCode: Request to https://baikal.example.com/dav.php/addressbooks/alex/default/ failed with code 401 and message: b'<?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:sabredav-version>4.6.0</s:sabredav-version>\n  <s:exception>Sabre\\DAV\\Exception\\NotAuthenticated</s:exception>\n  <s:message>No \'Authorization: Digest\' header found. Either the client didn\'t send one, or the server is misconfigured. Login was needed for privilege: {DAV:}read on addressbooks/alex/default</s:message>\n</d:error>\n'
```

**Comment by coinflipcoder** [comment]
Baikal uses digest auth. Check my fork for a working Baikal alternative: https://github.com/coinflipcoder/Calendar-Bday-Sync
